const STORE = 'synchub-v1';
const seeded = { contents: [
  { id: 'headline', title: 'Product-focused software engineer', category: 'Headline', text: 'Full stack engineer building clear, reliable products for people.', updatedAt: Date.now() - 86400000 },
  { id: 'skills', title: 'Core skills', category: 'Skills', text: 'JavaScript, React, Node.js, TypeScript, SQL, GitHub Actions', updatedAt: Date.now() - 3600000 }
], portals: [
  { id: 'linkedin', name: 'LinkedIn Profile', type: 'LinkedIn', url: 'https://www.linkedin.com/', contentIds: ['headline', 'skills'], synced: { headline: Date.now() - 86400000, skills: Date.now() - 3600000 } },
  { id: 'wellfound', name: 'Wellfound', type: 'Job board', url: 'https://wellfound.com/', contentIds: ['headline'], synced: { headline: Date.now() - 86400000 } }
] };
let state = loadState(), editingContent = null, editingPortal = null;
const $ = (s) => document.querySelector(s);
const id = () => crypto.randomUUID?.() || Math.random().toString(36).slice(2);
const escape = (value) => String(value).replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]));
function loadState(){ try { return JSON.parse(localStorage.getItem(STORE)) || structuredClone(seeded); } catch { return structuredClone(seeded); } }
function save(){ localStorage.setItem(STORE, JSON.stringify(state)); render(); }
function stale(portal, content){ return !portal.synced?.[content.id] || portal.synced[content.id] < content.updatedAt; }
function fmtDate(ms){ return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(ms); }
function refreshIcons(){ lucide.createIcons(); }
function render(){
  const staleItems = state.portals.flatMap(p => state.contents.filter(c => p.contentIds.includes(c.id) && stale(p,c)));
  $('#contentCount').textContent = state.contents.length; $('#contentTabCount').textContent = state.contents.length;
  $('#portalCount').textContent = state.portals.length; $('#portalTabCount').textContent = state.portals.length;
  $('#staleCount').textContent = staleItems.length; $('#staleLabel').textContent = staleItems.length ? `${staleItems.length} assigned item${staleItems.length === 1 ? '' : 's'} need attention` : 'Everything is up to date';
  renderContent(); renderPortals(); refreshIcons();
}
function renderContent(){ const query=$('#searchInput').value.toLowerCase(), filter=$('#categoryFilter').value; const list=state.contents.filter(c=>(filter==='all'||c.category===filter)&&(`${c.title} ${c.text}`).toLowerCase().includes(query)); const grid=$('#contentGrid'); if(!list.length){ grid.innerHTML=$('#emptyState').innerHTML; return; } grid.innerHTML=list.map(c=>`<article class="content-card"><div class="card-top"><span class="category">${escape(c.category)}</span><div class="card-actions"><button class="icon-button" data-edit-content="${c.id}" title="Edit content"><i data-lucide="pencil"></i></button><button class="icon-button" data-delete-content="${c.id}" title="Delete content"><i data-lucide="trash-2"></i></button></div></div><h2>${escape(c.title)}</h2><div class="content-text">${escape(c.text)}</div><div class="card-foot"><span>Updated ${fmtDate(c.updatedAt)}</span><span>${state.portals.filter(p=>p.contentIds.includes(c.id)).length} portal(s)</span></div></article>`).join(''); }
function renderPortals(){ const list=$('#portalList'); if(!state.portals.length){ list.innerHTML=$('#emptyState').innerHTML.replace('Nothing here yet','No portals yet').replace('Add your first item','Add a job portal'); return; } list.innerHTML=state.portals.map(p=>{const assigned=state.contents.filter(c=>p.contentIds.includes(c.id)); const isStale=assigned.some(c=>stale(p,c)); return `<article class="portal-card"><div class="portal-head"><div class="portal-logo">${escape(p.name.slice(0,2).toUpperCase())}</div><div class="portal-info"><div class="portal-title"><h2>${escape(p.name)}</h2><span class="type-chip">${escape(p.type)}</span><span class="status ${isStale?'stale':'fresh'}">${isStale?'Needs update':'Updated'}</span></div><a class="portal-link" target="_blank" rel="noreferrer" href="${escape(p.url)}">${escape(p.url)} <i data-lucide="external-link"></i></a></div><div class="card-actions"><button class="icon-button" data-edit-portal="${p.id}" title="Configure portal"><i data-lucide="settings-2"></i></button><button class="icon-button" data-delete-portal="${p.id}" title="Delete portal"><i data-lucide="trash-2"></i></button></div></div><div class="portal-body"><h3>ASSIGNED CONTENT & SYNC STATUS (${assigned.length})</h3><div class="assigned-list">${assigned.length?assigned.map(c=>`<div class="assigned-item"><div><strong>${escape(c.title)}</strong><span>${escape(c.text)}</span></div><div class="assigned-actions"><span class="status ${stale(p,c)?'stale':'fresh'}">${stale(p,c)?'Needs update':'Updated'}</span><button class="mini-btn ${stale(p,c)?'update':''}" data-mark="${p.id}|${c.id}">${stale(p,c)?'Mark updated':'Mark stale'}</button></div></div>`).join(''):'<div class="empty-state"><p>No content is assigned to this portal. Use the settings button to choose some.</p></div>'}</div></div></article>`; }).join(''); }
function openContent(item){ editingContent=item||null; $('#contentDialogTitle').textContent=item?'Edit content':'Add content'; $('#contentSubmit').textContent=item?'Save changes':'Save content'; $('#contentTitle').value=item?.title||''; $('#contentCategory').value=item?.category||'Headline'; $('#contentText').value=item?.text||''; $('#contentDialog').showModal(); }
function assignmentMarkup(selected=[]){ const container=$('#assignmentList'); container.innerHTML=state.contents.length?state.contents.map(c=>`<label class="assignment"><span>${escape(c.title)}<small>${escape(c.category)} · ${escape(c.text.slice(0,90))}</small></span><input type="checkbox" value="${c.id}" ${selected.includes(c.id)?'checked':''}></label>`).join(''):'<div class="empty-state"><p>Add content first, then it can be selected here.</p></div>'; updateAssignmentCount(); }
function updateAssignmentCount(){ $('#assignmentCount').textContent=`${$('#assignmentList input:checked').length} selected`; }
function openPortal(item){ editingPortal=item||null; $('#portalDialogTitle').textContent=item?'Configure portal':'Add job portal'; $('#portalSubmit').textContent=item?'Save changes':'Save portal'; $('#portalName').value=item?.name||''; $('#portalType').value=item?.type||'LinkedIn'; $('#portalUrl').value=item?.url||''; assignmentMarkup(item?.contentIds||[]); $('#portalDialog').showModal(); }
function getGithubSettings(){ return { token: sessionStorage.getItem('synchub-token') || '', repo: localStorage.getItem('synchub-repo') || '', branch: localStorage.getItem('synchub-branch') || 'main', path: localStorage.getItem('synchub-path') || 'synchub-data.json' }; }
function openGithub(){ const s=getGithubSettings(); $('#githubToken').value=s.token; $('#githubRepo').value=s.repo; $('#githubBranch').value=s.branch; $('#githubPath').value=s.path; $('#syncStatus').textContent=''; $('#githubDialog').showModal(); }
function githubSettings(){ const settings={token:$('#githubToken').value.trim(),repo:$('#githubRepo').value.trim(),branch:$('#githubBranch').value.trim(),path:$('#githubPath').value.trim()}; sessionStorage.setItem('synchub-token',settings.token); localStorage.setItem('synchub-repo',settings.repo); localStorage.setItem('synchub-branch',settings.branch); localStorage.setItem('synchub-path',settings.path); return settings; }
async function githubRequest(mode){ const s=githubSettings(), msg=$('#syncStatus'); if(!s.token||!s.repo||!s.branch||!s.path){ msg.textContent='Add your token, repository, branch, and file path.'; msg.className='sync-status error'; return; } msg.textContent=mode==='save'?'Saving data to GitHub...':'Loading data from GitHub...'; msg.className='sync-status'; const url=`https://api.github.com/repos/${s.repo}/contents/${s.path}?ref=${encodeURIComponent(s.branch)}`; const headers={Authorization:`Bearer ${s.token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}; try { if(mode==='load'){ const r=await fetch(url,{headers}); if(!r.ok)throw new Error((await r.json()).message||r.statusText); const data=await r.json(); const bytes=Uint8Array.from(atob(data.content.replace(/\n/g,'')),char=>char.charCodeAt(0)); state=JSON.parse(new TextDecoder().decode(bytes)); save(); msg.textContent='Loaded your data from GitHub.'; msg.className='sync-status success'; } else { const existing=await fetch(url,{headers}); let sha; if(existing.ok)sha=(await existing.json()).sha; else if(existing.status!==404)throw new Error((await existing.json()).message||existing.statusText); const bytes=new TextEncoder().encode(JSON.stringify(state,null,2)); let binary=''; bytes.forEach(byte=>binary+=String.fromCharCode(byte)); const content=btoa(binary); const r=await fetch(url,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({message:'Sync SyncHub profile data',content,branch:s.branch,...(sha?{sha}:{})})}); if(!r.ok)throw new Error((await r.json()).message||r.statusText); msg.textContent='Saved. Your repository now has the latest data.'; msg.className='sync-status success'; } } catch(error){ msg.textContent=`GitHub sync failed: ${error.message}`; msg.className='sync-status error'; } }
document.addEventListener('click',e=>{const target=e.target.closest('button'); if(!target)return; if(target.dataset.close)$('#'+target.dataset.close).close(); if(target.id==='addContentBtn')openContent(); if(target.id==='addPortalBtn')openPortal(); if(target.id==='githubBtn')openGithub(); if(target.id==='exportBtn'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='synchub-data.json';a.click();URL.revokeObjectURL(a.href);} if(target.dataset.editContent)openContent(state.contents.find(c=>c.id===target.dataset.editContent)); if(target.dataset.editPortal)openPortal(state.portals.find(p=>p.id===target.dataset.editPortal)); if(target.dataset.deleteContent){const content=state.contents.find(c=>c.id===target.dataset.deleteContent); if(confirm(`Delete “${content.title}”? It will also be removed from every portal.`)){state.contents=state.contents.filter(c=>c.id!==content.id);state.portals.forEach(p=>{p.contentIds=p.contentIds.filter(i=>i!==content.id);delete p.synced[content.id];});save();}} if(target.dataset.deletePortal&&confirm('Delete this portal?')){state.portals=state.portals.filter(p=>p.id!==target.dataset.deletePortal);save();} if(target.dataset.mark){const [portalId,contentId]=target.dataset.mark.split('|'),p=state.portals.find(x=>x.id===portalId),c=state.contents.find(x=>x.id===contentId);if(stale(p,c))p.synced[contentId]=Date.now();else p.synced[contentId]=0;save();} if(target.id==='saveGithubBtn')githubRequest('save'); if(target.id==='loadGithubBtn')githubRequest('load');});
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===tab));$('#contentView').classList.toggle('hidden',tab.dataset.view!=='content');$('#portalsView').classList.toggle('hidden',tab.dataset.view!=='portals');}));
$('#searchInput').addEventListener('input',renderContent); $('#categoryFilter').addEventListener('change',renderContent); $('#assignmentList').addEventListener('change',updateAssignmentCount);
$('#contentForm').addEventListener('submit',e=>{e.preventDefault();const now=Date.now(),data={id:editingContent?.id||id(),title:$('#contentTitle').value.trim(),category:$('#contentCategory').value,text:$('#contentText').value.trim(),updatedAt:now};if(editingContent){state.contents=state.contents.map(c=>c.id===data.id?data:c);}else state.contents.push(data);save();$('#contentDialog').close();});
$('#portalForm').addEventListener('submit',e=>{e.preventDefault();const contentIds=[...$('#assignmentList input:checked')].map(i=>i.value), previous=editingPortal?.synced||{}, synced={};contentIds.forEach(cid=>synced[cid]=previous[cid]||Date.now());const data={id:editingPortal?.id||id(),name:$('#portalName').value.trim(),type:$('#portalType').value,url:$('#portalUrl').value.trim(),contentIds,synced};if(editingPortal)state.portals=state.portals.map(p=>p.id===data.id?data:p);else state.portals.push(data);save();$('#portalDialog').close();});
$('#importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!Array.isArray(imported.contents)||!Array.isArray(imported.portals))throw new Error('That file does not look like SyncHub data.');state=imported;save();alert('Your data was imported.');}catch(error){alert(error.message);}e.target.value='';});
render();
